services:
  db:
    image: postgres:17-alpine
    container_name: stayhub_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: stayhub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    image: oven/bun:1
    container_name: stayhub_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:mypassword@db:5432/stayhub
    volumes:
      - .:/app
    working_dir: /app
    command: bun run src/index.ts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: